name: Required Code Review
on: 
  pull_request_review:
  pull_request:
    types: [ synchronize, opened, edited, closed, reopeend, review_requested, ready_for_review ]
    
jobs:
  check:
    name: Required Code Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Required Code review
        uses: Automatic/action-required-review@v3
